# Generated by Django 3.2.6 on 2021-09-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_remove_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
    ]
